name: Terraform Test Pipeline

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  terraform:
    name: Test Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -no-color

      - name: Terraform Apply (Auto-approve)
        run: terraform apply -auto-approve -no-color

      - name: ✅ Print Success Message
        run: echo "✅ Terraform workflow completed successfully"
